version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: convo
      POSTGRES_USER: convo
      POSTGRES_DB: convo
    ports: ["5432:5432"]
    volumes: [pg:/var/lib/postgresql/data]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: [minio:/data]
volumes:
  pg: {}
  minio: {}
